"""CI guard: the report regenerated by judge_b.sh must carry the headline numbers the repo committed.

judge_b.sh regenerates report/metrics.json over the shipped runs; git holds the committed version. If a shipped log
or the replay code changed without the report, the two differ and this fails.
"""
import json
import subprocess
import sys

KEYS = [
    ("readings", "headline", "metrics", "total_return"),
    ("readings", "headline", "metrics", "sharpe"),
    ("readings", "headline", "metrics", "max_dd"),
    ("readings", "increment", "increment", "sharpe_diff"),
    ("readings", "increment", "verdict"),
    ("readings", "information", "verdict"),
    ("readings", "signal_tests", "n_significant"),
    ("live", "n_records"),
    ("live", "reconcile", "n_identical"),
]


def dig(o, path):
    for k in path:
        o = o[k]
    return o


committed = json.loads(subprocess.check_output(["git", "show", "HEAD:report/metrics.json"], text=True))
regenerated = json.load(open("report/metrics.json"))
bad = []
for path in KEYS:
    a, b = dig(committed, path), dig(regenerated, path)
    same = abs(a - b) < 1e-9 if isinstance(a, float) and isinstance(b, float) else a == b
    print(("ok      " if same else "DIFFERS ") + ".".join(path) + f": committed {a!r}, regenerated {b!r}")
    if not same:
        bad.append(path)
sys.exit(1 if bad else 0)
